site_name: Box3 社区文档
repo_url: https://github.com/alan-best/box3-docs
edit_uri: edit/main/docs/
repo_name: box3-docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
    - search.suggest
    - search.highlight
  language: zh
  palette:
    # primary: blue
    # accent: indigo
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: 暗色模式
  custom_dir: overrides
extra_css:
  - _assets/icons.css
  - _assets/global.css

extra_javascript:
  - _assets/iconsParser.js
  - _assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - pymdownx.tilde
  - tables
plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
nav:
  - 主页:
      - 介绍:
          - 欢迎: index.md
          - 关于文档: about.md
          - 更新: changes.md
  - 学习:
      - learn/index.md
      - 粒子特效:
          - learn/particle/index.md
      - JavaScript:
          - learn/js/index.md
          - 基础教程:
              - learn/js/base/index.md
              - 开始: learn/js/base/index.md
              - Hello, World!: learn/js/base/01-hello-world.md
              - 欢迎玩家: learn/js/base/02-greeting.md
      - 大佬の宝典:
          - SQL快速入门: learn/community-articles/Nomen-sql.md
          - OOP（面向对象编程）快速入门: learn/community-articles/Nomen-oop.md
          - 如何优雅地写注释: learn/community-articles/Nomen-comment.md
          - 快速上手函数: learn/community-articles/Nomen-function.md
  - 实例教程:
      - example/index.md
      - LightDotCutter 简单PVE游戏:
          - 起步: example/light-dot-cutter/01-start.md
          - 生成敌人: example/light-dot-cutter/02-setup-enemy.md
      #     - 实现玩家攻击: example/light-dot-cutter/03-attack.md
      #     - 添加敌人和玩家的血量: example/light-dot-cutter/04-health.md
      #     - 设置奖励: example/light-dot-cutter/05-reward.md
      #     - 添加特效: example/light-dot-cutter/06-effect.md
      #     - 重构和扩展: example/light-dot-cutter/07-extra.md
      #     - 优化: example/light-dot-cutter/08-optimization.md
  - API参考:
      - api/index.md
      - <icon name='namespace'>图标参考</icon>: api/icons.md
      - <icon name='object'>世界</icon>: api/world.md
      - <icon name='object'>方块</icon>: api/voxels.md
      - <icon name='class'>实体</icon>: api/entity.md
      - <icon name='class'>玩家</icon>: api/player.md
      - <icon name='event'>事件</icon>:
          - <def>Box3TickEvent</def>: api/event/Box3TickEvent.md
          - <def>Box3RespawnEvent</def>: api/event/Box3RespawnEvent.md
          - <def>Box3DamageEvent</def>: api/event/Box3DamageEvent.md
          - <def>Box3DieEvent</def>: api/event/Box3DieEvent.md
          - <def>Box3PlayerEntityEvent</def>: api/event/Box3PlayerEntityEvent.md
          - <def>Box3EntityEvent</def>: api/event/Box3EntityEvent.md

      - <icon name='enum'>数据库</icon>: api/database.md
      - <icon name='type'>结构类型</icon>:
          - <icon name='namespace'>基本数据类型</icon>:
              - <def>String</def>: api/type/base/String.md
              - <def>Number</def>: api/type/base/Number.md
              - <def>Boolean</def>: api/type/base/Boolean.md
              - <def>Partial</def>: api/type/base/Partial.md
              - <def>URL</def>: api/type/base/URL.md
          - <def>Box3Vector3</def>: api/type/Box3Vector3.md
          - <def>Box3EventChannel</def>: api/type/Box3EventChannel.md
          - <def>Box3EventFuture</def>: api/type/Box3EventFuture.md
          - <def>Box3EntityConfig</def>: api/type/Box3EntityConfig.md
          - <def>Box3SelectorString</def>: api/type/Box3SelectorString.md
          - <def>Box3RaycastOptions</def>: api/type/Box3RaycastOptions.md
          - <def>Box3Bounds3</def>: api/type/Box3Bounds3.md
          - <def>Box3RGBColor</def>: api/type/Box3RGBColor.md
          - <def>Box3SoundEffect</def>: api/type/Box3SoundEffect.md

      - <icon name='signature'>动画</icon>:
          - <def>Box3WorldKeyframe</def>: api/type/Box3WorldKeyframe.md
          - <def>Box3AnimationPlaybackConfig</def>: api/type/Box3AnimationPlaybackConfig.md
          - <def>Box3Animation</def>: api/type/Box3Animation.md
          - <def>Box3EntityKeyframe</def>: api/type/Box3EntityKeyframe.md
          - <def>Box3PlayerKeyframe</def>: api/type/Box3PlayerKeyframe.md
# - Getting started:
#   - Installation: getting-started.md
#   - Creating your site: creating-your-site.md
#   - Publishing your site: publishing-your-site.md
#   - Customization: customization.md
#   - Browser support: browser-support.md
#   - Philosophy: philosophy.md
#   - Alternatives: alternatives.md
#   - License: license.md
#   - Changelog:
#     - changelog/index.md
#     - How to upgrade: upgrade.md
# - Setup:
#   - Changing the colors: setup/changing-the-colors.md
#   - Changing the fonts: setup/changing-the-fonts.md
#   - Changing the language: setup/changing-the-language.md
#   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#   - Ensuring data privacy: setup/ensuring-data-privacy.md
#   - Setting up navigation: setup/setting-up-navigation.md
#   - Setting up site search: setup/setting-up-site-search.md
#   - Setting up site analytics: setup/setting-up-site-analytics.md
#   - Setting up social cards: setup/setting-up-social-cards.md
#   - Setting up tags: setup/setting-up-tags.md
#   - Setting up versioning: setup/setting-up-versioning.md
#   - Setting up the header: setup/setting-up-the-header.md
#   - Setting up the footer: setup/setting-up-the-footer.md
#   - Adding a git repository: setup/adding-a-git-repository.md
#   - Adding a comment system: setup/adding-a-comment-system.md
#   - Building for offline usage: setup/building-for-offline-usage.md
#   - Extensions:
#     - setup/extensions/index.md
#     - Python Markdown: setup/extensions/python-markdown.md
#     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
# - Reference:
#   - reference/index.md
#   - Admonitions: reference/admonitions.md
#   - Annotations: reference/annotations.md
#   - Buttons: reference/buttons.md
#   - Code blocks: reference/code-blocks.md
#   - Content tabs: reference/content-tabs.md
#   - Data tables: reference/data-tables.md
#   - Diagrams: reference/diagrams.md
#   - Footnotes: reference/footnotes.md
#   - Formatting: reference/formatting.md
#   - Grids: reference/grids.md
#   - Icons, Emojis: reference/icons-emojis.md
#   - Images: reference/images.md
#   - Lists: reference/lists.md
#   - MathJax: reference/mathjax.md
#   - Tooltips: reference/tooltips.md
# - Insiders:
#   - insiders/index.md
#   - Getting started:
#     - Installation: insiders/getting-started.md
#     - Changelog: insiders/changelog.md
# - Blog:
#   - blog/index.md
#   - 2022:
#     - blog/2022/chinese-search-support.md
#   - 2021:
#     - blog/2021/the-past-present-and-future.md
#     - blog/2021/excluding-content-from-search.md
#     - blog/2021/search-better-faster-smaller.md
